In [1]:
import tensorflow as tf
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = 2

Constant Tensor

In [2]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


Set Tensor shape and data type

In [3]:
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


Rank 1 Tensor

In [4]:
x = tf.constant([1,2,3])
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


Rank 2 Tensor

In [5]:
x = tf.constant([[1,2,3], [4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


Fill Tensor with values

In [6]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [7]:
x = tf.zeros((3,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [8]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


Fill Tensor with random values from normal distribution

In [9]:
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[ 0.03457506 -0.4441647   0.983489  ]
 [-0.17593701 -0.6014156  -0.52971023]
 [ 1.9491493   0.4385658  -3.135785  ]], shape=(3, 3), dtype=float32)


Fill Tensor with random values from a uniform distribution

In [12]:
x = tf.random.uniform((3,3), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.9036478  0.73779273 0.2153796 ]
 [0.5775275  0.27129877 0.1509862 ]
 [0.82239115 0.0647366  0.40787518]], shape=(3, 3), dtype=float32)


In [13]:
x = tf.range(10)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


Casting Tensors

**Note `dtype=float32` in print statement

In [15]:
x = tf.cast(x, dtype=tf.float32)
print(x)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


## Operations on Tensors

Tensor operations are element wise, meaning:

X=[X1, X2, X3] and Y=[Y1, Y2, Y3]

:=
X + Y = [X1 + Y1, X2 + Y2, X3 + Y3]

In [16]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

Adding Tensors

In [17]:
z = tf.add(x,y)
print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [18]:
z = x + y
print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


Substracting Tensors

In [19]:
z = tf.subtract(x, y)
print(z)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [20]:
z = x - y
print(z)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


Multiplying Tensors

In [21]:
z = tf.multiply(x,y)
print(z)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [22]:
z = x * y
print(z)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


Dot product

In [23]:
z = tf.tensordot(x,y, axes=1)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


Exponential Product

In [25]:
z = x ** 3
print(z)

tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)


## Operations on Matrices
Recall that in order to perform the cross product between matrtrix A and matrix B, the number of columns of matrix A must match the number of row in matrix B

In [29]:
x = tf.random.normal((3,4))
y = tf.random.normal((4,4))

z = tf.matmul(x,y)
print(z)

tf.Tensor(
[[-1.7600662e+00  5.0628185e-04  5.0375156e+00  1.5360110e+00]
 [ 2.1229014e+00  1.7487676e+00  6.6720939e-01  7.9340136e-01]
 [-1.1249813e+00 -8.6749339e-01  2.5167665e+00  6.5710533e-01]], shape=(3, 4), dtype=float32)


Indexing and Slicing

In [30]:
x = tf.constant([[1,2,3], [4,5,6]])
print(x[0])

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [31]:
print(x[:, 0]) # all rows, col 0
print(x[0, :]) # row 0, all columns

tf.Tensor([1 4], shape=(2,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [32]:
print(x[0, 1:2]) 

tf.Tensor([2], shape=(1,), dtype=int32)


Reshaping Tensors

In [33]:
x = tf.random.normal((2,3))
print(x)

tf.Tensor(
[[ 0.5299771  0.7830578  1.9857326]
 [ 0.68675    1.0036954 -1.2553706]], shape=(2, 3), dtype=float32)


In [34]:
x = tf.reshape(x, (3,2))
print(x)

tf.Tensor(
[[ 0.5299771  0.7830578]
 [ 1.9857326  0.68675  ]
 [ 1.0036954 -1.2553706]], shape=(3, 2), dtype=float32)


Converting Tensors to Numpy Arrays (and viceversa)


In [35]:
x = x.numpy()
print(x, type(x))

[[ 0.5299771  0.7830578]
 [ 1.9857326  0.68675  ]
 [ 1.0036954 -1.2553706]] <class 'numpy.ndarray'>


In [37]:
x = tf.convert_to_tensor(x)
print(x, type(x))

tf.Tensor(
[[ 0.5299771  0.7830578]
 [ 1.9857326  0.68675  ]
 [ 1.0036954 -1.2553706]], shape=(3, 2), dtype=float32) <class 'tensorflow.python.framework.ops.EagerTensor'>


String Tensors

In [38]:
names = tf.constant(["Rodrigo", "Morales"])
print(names)

tf.Tensor([b'Rodrigo' b'Morales'], shape=(2,), dtype=string)


Tensor Variable

It is mutable contrary to constant tensors which are immutable. They are used for instance for model hyper params.

In [39]:
x = tf.Variable([1,2,3])
print(x)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
